# Generated by Django 3.0.1 on 2020-01-04 21:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.crypto
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GiftList',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_link', models.SlugField(default=django.utils.crypto.get_random_string, editable=False)),
                ('contributor_link', models.SlugField(default=django.utils.crypto.get_random_string, editable=False)),
                ('recipient_link', models.SlugField(default=django.utils.crypto.get_random_string, editable=False)),
                ('title', models.CharField(max_length=120)),
                ('recipient', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('cost', models.IntegerField()),
                ('completed', models.BooleanField(default=False)),
                ('completed_on', models.DateTimeField(null=True)),
                ('completed_by', models.CharField(blank=True, max_length=120, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=120)),
                ('gift_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gyft.GiftList')),
            ],
        ),
    ]
